name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          cache: "npm"
          cache-dependency-path: Final-Project/package-lock.json

      - name: Install dependencies
        working-directory: ./Final-Project
        run: npm ci
      - name: Generate Prisma Client
        working-directory: ./Final-Project
        run: npx prisma generate
        env:
          PRISMA_DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
      - name: Run Prisma Migrations
        working-directory: ./Final-Project
        run: npx prisma migrate deploy
        env:
          PRISMA_DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
      - name: Run Biome Lint
        working-directory: ./Final-Project
        run: npx biome check .

      # Uncomment this block only when running with nektos/act for local GitHub Actions testing
      # - name: Install Xvfb (required for Cypress)
      #   if: runner.os == 'Linux'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
      - name: Build application
        working-directory: ./Final-Project
        run: npm run build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     working-directory: ./Final-Project
      #     start: npm start
      #   env:
      #     NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      #     CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
