name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.21.1"
          cache: "npm"
          cache-dependency-path: Final-Project/package-lock.json

      - name: Install dependencies
        working-directory: ./Final-Project
        run: npm ci
        env:
          PRISMA_DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
      - name: Run Prisma Migrations
        working-directory: ./Final-Project
        run: npx prisma migrate deploy
        env:
          PRISMA_DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
      - name: Run Biome Lint
        working-directory: ./Final-Project
        run: npx biome check .

      # Required for Cypress when running with nektos/act
      - name: Install Xvfb (required for Cypress)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command-prefix: "--"
          working-directory: ./Final-Project
          build: npm run build
          start: npm start
        env:
          TZ: America/Bogota

          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_CLERK_BASE_URL: ${{ secrets.NEXT_PUBLIC_CLERK_BASE_URL }}

          NEXT_PUBLIC_STREAM_API_KEY: ${{ secrets.NEXT_PUBLIC_STREAM_API_KEY }}
          STREAM_SECRET_KEY: ${{ secrets.STREAM_SECRET_KEY }}
          NEXT_PUBLIC_STREAM_BASE_URL: ${{ secrets.NEXT_PUBLIC_STREAM_BASE_URL }}

          CYPRESS_CLERK_IDENTIFIER: ${{ secrets.CYPRESS_CLERK_IDENTIFIER }}
          CYPRESS_CLERK_PASSWORD: ${{ secrets.CYPRESS_CLERK_PASSWORD }}
          CYPRESS_CREATED_BY_ID: ${{ secrets.CYPRESS_CREATED_BY_ID }}

          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

          PRISMA_DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
      # Builds a Docker image
      - name: Build Docker Image
        run: docker build -t talk2-backend ./Final-Project
